global:
  # service selector label key to target kube controller manager pods
  k8sComponentLabelKey: k8s-app

# on what port are the metrics exposed by etcd
controllerManagerPort: 10252
# for deployments that have etcd deployed outside of the cluster, list their adresses here
endpoints: []
# Are we talking http or https?
scheme: http
# default rules are in templates/kube-controller-manager.rules.yaml
# prometheusRules: {}
